apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-job-assistant-admin
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs:
        - get
        - list
        - create
        - update
        - watch
        - delete
        - patch
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - deletecollection
