apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-job-assistant-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-job-assistant-admin
subjects:
  - kind: ServiceAccount
    name: default   # created by Kube in the namespace
