apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-job-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-job-assistant
  template:
    metadata:
      labels:
        app: kube-job-assistant
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: kja
          image: kja:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "400m"
              memory: "500Mi"
            limits:
              cpu: "400m"
              memory: "500Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
