resources:
  - deployment.yaml
  - service.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml

labels:
  - pairs:
      app: kube-job-assistant

images:
  - name: your.registry.com/your-org/your-image
    newTag: latest
