apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-job-assistant-testing
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs:
      - deletecollection
