name: Build and Push Kubernetes Job Assistant

on:
  push:
    branches:
      - master
#    paths:
#      - k8s_job_assistant

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: dockerhub.io
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: k8s_job_assistant
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/remipichon/kja:latest
